<?xml version="1.0"?>
<package format="3">
  <name>agconav_worlds</name>
  <version>0.0.1</version>

  <description>
    Gazebo worlds for the AG-CoNav multi-robot simulation.
  </description>

  <maintainer email="lee@example.com">lee</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>