frame_id: map
altitude: 84.0
strip_spacing: 32.581
num_waypoints: 10
waypoints:
- position:
    x: -38.6
    y: -166.1
    z: 84.0
  orientation: &id001
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 61.4
    y: -166.1
    z: 84.0
  orientation: *id001
- position:
    x: 61.4
    y: -141.1
    z: 84.0
  orientation: &id002
    x: 0.0
    y: 0.0
    z: 1.0
    w: 6.123233995736766e-17
- position:
    x: -38.6
    y: -141.1
    z: 84.0
  orientation: *id002
- position:
    x: -38.6
    y: -116.1
    z: 84.0
  orientation: &id003
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 61.4
    y: -116.1
    z: 84.0
  orientation: *id003
- position:
    x: 61.4
    y: -91.1
    z: 84.0
  orientation: &id004
    x: 0.0
    y: 0.0
    z: 1.0
    w: 6.123233995736766e-17
- position:
    x: -38.6
    y: -91.1
    z: 84.0
  orientation: *id004
- position:
    x: -38.6
    y: -66.1
    z: 84.0
  orientation: &id005
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
- position:
    x: 61.4
    y: -66.1
    z: 84.0
  orientation: *id005
