<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>agconav_navigation</name>
  <version>0.0.0</version>
  <description>Navigation module for AG-CoNav (Module C)</description>
  <maintainer email="lsb@todo.todo">lsb</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs_py</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros_py</depend>
  <depend>action_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>lifecycle_msgs</depend>
  <!-- quadruped_ros2_control 의 RL 컨트롤러 입력 타입 -->
  <depend>control_input_msgs</depend>
  <exec_depend>python3-numpy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
