# 1. IMU 데이터 연결
- ros_topic_name: "imu"
  gz_topic_name: "/imu" # 앞서 터미널 목록에서 확인된 토픽 (필요시 확인 후 수정)
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# 2. GPS 데이터 연결
- ros_topic_name: "gps/fix"
  gz_topic_name: "/model/leg/navsat" # GPS 센서를 확인한 후 실제 토픽 이름으로 수정해야 함
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "odom"
  gz_topic_name: "/model/leg/odometry" # Gazebo 실제 odom 토픽 이름으로 수정 필요
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS