- ros_topic_name: "points"
  gz_topic_name: "/model/robot/sensor/lidar/scan/points" # need to find
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked" # Gazebo 버전에 따라 ignition.msgs... 일 수도 있음 need to check
  direction: GZ_TO_ROS 