/**:
  ros__parameters:
    use_sim_time: true
    yaw_diff_threshold_rad: 0.1
    covariance_threshold: 0.05
    check_rate_hz: 1.0
    odom_topic: "odom"
    imu_topic: "imu"
    status_topic: "yaw_check_status"
