"""scan.launch.py — fly the drone's lawnmower scan over Seongdong_gu_100x100 with
the GUI up, and record the raw LiDAR + IMU stream for GLIM.

Every flight module is agconav_drone's, unmodified: drone_path_player,
drone_pose_controller and their yaml. What changes for a test world is the pose
range -- the waypoints in config/path_100x100.yaml, generated by agconav_drone's
own generate_path.py from this world's heightmap extent. Altitude (84 m), cruise
speed (8 m/s), strip spacing and the turn behaviour are therefore identical to a
full-world run, and the same setup points back at the full world unchanged.

What this records is the *input* GLIM needs -- raw `/drone/points` scans and
`/drone/imu` -- not the elevation-map output the existing maps/ bags hold. The
elevation mapper and map saver are deliberately not started; this launch exists
to produce a SLAM input bag.

    ros2 launch agconav_test_worlds scan.launch.py

    ros2 launch agconav_test_worlds scan.launch.py record:=false headless:=true
"""

import os

from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    IncludeLaunchDescription,
    RegisterEventHandler,
    SetEnvironmentVariable,
    Shutdown,
)
from launch.conditions import IfCondition, UnlessCondition
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

WORLD_NAME = "Seongdong_gu"          # kept from the source world, so world:= args still match
WORLD_DIR = "Seongdong_gu_100x100"


def generate_launch_description():
    test_worlds_share = get_package_share_directory("agconav_test_worlds")
    drone_share = get_package_share_directory("agconav_drone")  # pose controller config
    worlds_share = get_package_share_directory("agconav_worlds")
    description_share = get_package_share_directory("agconav_description")
    bringup_share = get_package_share_directory("agconav_bringup")
    ros_gz_sim_share = get_package_share_directory("ros_gz_sim")

    record = LaunchConfiguration("record")
    headless = LaunchConfiguration("headless")
    bag_output = LaunchConfiguration("bag_output")
    use_sim_time = LaunchConfiguration("use_sim_time")

    declare_args = [
        DeclareLaunchArgument(
            "record", default_value="true",
            description="rosbag2로 /drone/points·/drone/imu를 기록할지 여부"),
        DeclareLaunchArgument(
            "headless", default_value="false",
            description="GUI 없이 서버만 띄운다 (진행 상황을 보려면 false)"),
        DeclareLaunchArgument(
            "bag_output",
            default_value=os.path.join(os.getcwd(), "bags", "drone_scan_100x100"),
            description="기록할 bag 디렉터리 (이미 있으면 rosbag2가 거부한다)"),
        DeclareLaunchArgument(
            "use_sim_time", default_value="true", description="Gazebo 시계 사용"),
    ]

    world_path = os.path.join(test_worlds_share, "worlds", WORLD_DIR, WORLD_DIR + ".world")

    # The world pulls in model://agconav_drone, and keeps the bump_*/ramp_* refs
    # from its parent world, so both model roots have to stay on the path.
    gz_dirs = [
        os.path.join(description_share, "models"),
        os.path.join(worlds_share, "models"),
    ]
    if os.environ.get("GZ_SIM_RESOURCE_PATH"):
        gz_dirs.append(os.environ["GZ_SIM_RESOURCE_PATH"])
    set_gz_resource_path = SetEnvironmentVariable(
        name="GZ_SIM_RESOURCE_PATH", value=os.pathsep.join(gz_dirs))

    gazebo_gui = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(ros_gz_sim_share, "launch", "gz_sim.launch.py")),
        launch_arguments={"gz_args": [world_path, " -r"]}.items(),
        condition=UnlessCondition(headless),
    )
    gazebo_headless = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(ros_gz_sim_share, "launch", "gz_sim.launch.py")),
        launch_arguments={"gz_args": [world_path, " -r -s"]}.items(),
        condition=IfCondition(headless),
    )

    clock_bridge = Node(
        package="ros_gz_bridge", executable="parameter_bridge",
        name="scan_clock_bridge", output="screen",
        arguments=["/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock"],
    )

    # drone_pose_controller drives the drone by calling this service.
    set_pose_bridge = Node(
        package="ros_gz_bridge", executable="parameter_bridge",
        name="scan_set_pose_bridge", output="screen",
        arguments=["/world/%s/set_pose@ros_gz_interfaces/srv/SetEntityPose" % WORLD_NAME],
    )

    # Only the drone's sensors -- the ground robots are not in this world.
    sensor_bridge = Node(
        package="ros_gz_bridge", executable="parameter_bridge",
        name="scan_drone_sensor_bridge", output="screen",
        parameters=[{"use_sim_time": use_sim_time}],
        arguments=[
            "/drone/points/points@sensor_msgs/msg/PointCloud2[gz.msgs.PointCloudPacked",
            "/drone/imu@sensor_msgs/msg/Imu[gz.msgs.IMU",
        ],
        remappings=[("/drone/points/points", "/drone/points")],
    )

    # Gazebo's own pose stream, kept off /tf so it cannot be mistaken for an
    # estimate: this is the ground truth GLIM's trajectory gets judged against.
    ground_truth_bridge = Node(
        package="ros_gz_bridge", executable="parameter_bridge",
        name="scan_ground_truth_bridge", output="screen",
        parameters=[{"use_sim_time": use_sim_time}],
        arguments=[
            "/world/%s/dynamic_pose/info@tf2_msgs/msg/TFMessage[gz.msgs.Pose_V" % WORLD_NAME,
        ],
        remappings=[("/world/%s/dynamic_pose/info" % WORLD_NAME, "/ground_truth/tf")],
    )

    # The drone is spawned from SDF, not URDF, so nothing else publishes this leg
    # of the chain. Values copied from agconav_drone/launch/drone_sim_test.launch.py.
    lidar_static_tf = Node(
        package="tf2_ros", executable="static_transform_publisher",
        name="drone_os1_lidar_static_tf", output="screen",
        arguments=[
            "--x", "0", "--y", "0", "--z", "-0.175406",
            "--roll", "0", "--pitch", "1.5708", "--yaw", "0",
            "--frame-id", "drone/base_link",
            "--child-frame-id", "drone/os1_lidar",
        ],
        parameters=[{"use_sim_time": use_sim_time}],
    )

    drone_pose_controller = Node(
        package="agconav_drone", executable="drone_pose_controller",
        name="drone_pose_controller", output="screen",
        parameters=[
            os.path.join(drone_share, "config", "drone_pose_controller.yaml"),
            {"world_name": WORLD_NAME, "entity_name": "X3", "use_sim_time": use_sim_time},
        ],
    )

    # agconav_drone's own player and its own yaml -- cruise speed, publish rate
    # and interpolation all stay as the full-world runs use them. Only the
    # waypoint file differs, and that file was produced by agconav_drone's own
    # generator reading this world's heightmap extent, so the scan range follows
    # the test box while everything else carries back unchanged.
    drone_path_player = Node(
        package="agconav_drone", executable="drone_path_player",
        name="drone_path_player", output="screen",
        parameters=[
            os.path.join(drone_share, "config", "drone_path_player.yaml"),
            {
                "path_file": os.path.join(test_worlds_share, "config",
                                          "path_100x100.yaml"),
                "use_sim_time": use_sim_time,
            },
        ],
    )

    bag_recorder = ExecuteProcess(
        cmd=[
            "ros2", "bag", "record", "-s", "mcap", "-o", bag_output,
            "/drone/points", "/drone/imu", "/tf", "/tf_static", "/ground_truth/tf",
        ],
        output="screen",
        condition=IfCondition(record),
    )

    # The heightmap here is small, but the same start-order trap applies: if the
    # drone starts being teleported before the world answers, the set_pose calls
    # are lost and the scan silently flies from the wrong place.
    wait_for_world = ExecuteProcess(
        cmd=[os.path.join(bringup_share, "scripts", "wait_for_world.sh"), WORLD_NAME, "180"],
        output="screen", name="wait_for_world",
    )

    def _on_world_ready(event, context):        # noqa: ARG001
        if event.returncode != 0:
            return [Shutdown(reason="world load timeout")]
        return [bag_recorder, drone_pose_controller, drone_path_player]

    start_after_world = RegisterEventHandler(
        OnProcessExit(target_action=wait_for_world, on_exit=_on_world_ready)
    )

    return LaunchDescription(
        declare_args + [
            set_gz_resource_path,
            gazebo_gui,
            gazebo_headless,
            clock_bridge,
            set_pose_bridge,
            sensor_bridge,
            ground_truth_bridge,
            lidar_static_tf,
            wait_for_world,
            start_after_world,
        ]
    )
